import type { Metadata } from "next";
import { Toaster } from "@/components/atoms/toaster";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="h-screen">
        <main className="flex h-full">
          {children}
          <Toaster />
        </main>
      </body>
    </html>
  );
}
